/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exo1 */

#ifndef _Included_exo1
#define _Included_exo1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     exo1
 * Method:    getPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_exo1_getPid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
